Repository Compiler-CampusMinden/CB-Vorlesung-Bachelor, pull requests merged in 2022-10, with the labels that each got.

#76 [ORGA] Bachelor: Finalise deadlines, rooms, schedule ...
  data/ba/schedule.yaml
  markdown/_index.ba.md
  markdown/assignments/sheet04.ba.md
  markdown/org/grading.ba.md
Labels: bug, vorlesungen

#77 [ORGA] Master: Finalise deadlines, rooms, schedule ...
  data/ma/schedule.yaml
  markdown/_index.ma.md
  markdown/org/grading.ma.md
Labels: bug, vorlesungen

#78 [ORGA] Fix URL to ILIAS and workload
  markdown/_index.ma.md
  markdown/org/images/modulbeschreibung.png
  markdown/org/images/modulbeschreibung_ba.png
  markdown/org/images/modulbeschreibung_ma.png
  markdown/org/syllabus.ba.md
  markdown/org/syllabus.ma.md
Labels: bug, vorlesungen

#81 [ORGA] fix grading ma
  markdown/org/grading.ma.md
Labels: bug, vorlesungen

#83 [FAQ] add initial FAQ (bachelor)
  markdown/org/faq.ba.md
Labels: bug, documentation, vorlesungen

#84 [FAQ] add initial FAQ (master)
  markdown/org/faq.ma.md
Labels: bug, documentation, vorlesungen

#85 [ORGA] Fix VL-Modus
  markdown/_index.ba.md
  markdown/_index.ma.md
  markdown/org/faq.ba.md
  markdown/org/faq.ma.md
Labels: bug, vorlesungen

#86 [VL] Update link to annotated slides (Lexing/Regular: Bachelor)
  markdown/frontend/lexing/regular.ba.md
Labels: bug, vorlesungen

#87 [VL] Update link to annotated slides (Lexing/Regular Master)
  markdown/frontend/lexing/regular.ma.md
Labels: bug, vorlesungen

#88 [VL] Add ANTLR Lexer
  markdown/frontend/lexing/antlr.ba.md
  markdown/frontend/lexing/antlr.ma.md
  markdown/frontend/lexing/src/Demo.g4
  markdown/frontend/lexing/src/Hello.g4
  markdown/frontend/lexing/src/Longest.g4
  markdown/frontend/lexing/src/Main.java
  markdown/frontend/lexing/src/Nongreedy.g4
  markdown/frontend/lexing/src/Order.g4
  markdown/frontend/lexing/src/env.sh
Labels: vorlesungen

#89 [P] add B01
  markdown/assignments/sheet01.ba.md
  markdown/assignments/sheet01.ma.md
Labels: aufgaben

#95 [VL] Fix Recursive Lexer: remove table caption (Hugo does not recognize it properly)
  markdown/frontend/lexing/recursive.ba.md
  markdown/frontend/lexing/recursive.ma.md
Labels: bug, vorlesungen

#91 [P] add B02
  markdown/assignments/sheet02.ba.md
  markdown/assignments/sheet02.ma.md
Labels: aufgaben

#94 [VL] Rework Lecture CFG (MA)
  markdown/frontend/parsing/cfg.ba.md
  markdown/frontend/parsing/cfg.ma.md
Labels: vorlesungen

#90 [P] add B03
  markdown/assignments/sheet03.ba.md
  markdown/assignments/sheet03.ma.md
Labels: aufgaben

#93 [VL] Add ANTLR Parser
  markdown/frontend/parsing/antlr.ba.md
  markdown/frontend/parsing/antlr.ma.md
  markdown/frontend/parsing/images/ParseTreeListener.png
  markdown/frontend/parsing/images/ParseTreeListener.uxf
  markdown/frontend/parsing/images/ParseTreeVisitor.png
  markdown/frontend/parsing/images/ParseTreeVisitor.uxf
  markdown/frontend/parsing/images/ParserRuleContext.png
  markdown/frontend/parsing/images/ParserRuleContext.uxf
  markdown/frontend/parsing/images/hello_ex1.png
  markdown/frontend/parsing/images/hello_ex2.png
  markdown/frontend/parsing/src/Hello.g4
  markdown/frontend/parsing/src/Main.java
  markdown/frontend/parsing/src/TestMyListener.java
  markdown/frontend/parsing/src/TestMyVisitor.java
  markdown/frontend/parsing/src/calc.g4
  markdown/frontend/parsing/src/env.sh
Labels: vorlesungen

#97 [VL] LL-Parser (Theory): Add annotated slides
  markdown/frontend/parsing/ll-parser-theory.ba.md
  markdown/frontend/parsing/ll-parser-theory.ma.md
Labels: bug, vorlesungen

#98 [VL] Attributierte Grammatiken: Add annotated slides
  markdown/frontend/semantics/attribgrammars.ba.md
  markdown/frontend/semantics/attribgrammars.ma.md
Labels: bug, vorlesungen
