Repository Compiler-CampusMinden/CB-Vorlesung-Bachelor, pull requests merged in 2022-11, with the labels that each got.

#99 [VL] LL-Parser-Theorie und Attributierte Grammatiken
  markdown/frontend/parsing/ll-parser-theory.ba.md
  markdown/frontend/parsing/ll-parser-theory.ma.md
  markdown/frontend/semantics/attribgrammars.ba.md
  markdown/frontend/semantics/attribgrammars.ma.md
Labels: bug, vorlesungen

#100 [VL] LL-Parser und Error-Recovery
  markdown/frontend/parsing/finalwords.ba.md
  markdown/frontend/parsing/finalwords.ma.md
  markdown/frontend/parsing/ll-advanced.ma.md
  markdown/frontend/parsing/ll-parser-impl.ba.md
  markdown/frontend/parsing/ll-parser-impl.ma.md
  markdown/frontend/parsing/recovery.ba.md
  markdown/frontend/parsing/recovery.ma.md
Labels: bug, vorlesungen

#101 [VL] Fix formatting (Error Recovery)
  markdown/frontend/parsing/recovery.ba.md
  markdown/frontend/parsing/recovery.ma.md
Labels: bug, vorlesungen

#106 [ORG] add url to 'We CAN virtuOWL' project
  README.md
  markdown/_index.ba.md
  markdown/_index.ma.md
Labels: bug, vorlesungen

#107 [VL] Interpreters
  markdown/backend/interpretation/astdriven-part1.ba.md
  markdown/backend/interpretation/astdriven-part1.ma.md
  markdown/backend/interpretation/astdriven-part2.ba.md
  markdown/backend/interpretation/astdriven-part2.ma.md
  markdown/backend/interpretation/images/ParseTreeListener.png
  markdown/backend/interpretation/images/ParseTreeListener.uxf
  markdown/backend/interpretation/images/ParseTreeVisitor.png
  markdown/backend/interpretation/images/ParseTreeVisitor.uxf
  markdown/backend/interpretation/syntaxdriven.ba.md
  markdown/backend/interpretation/syntaxdriven.ma.md
Labels: bug, vorlesungen

#108 [VL] Interpreter and Assignments
  markdown/backend/interpretation/astdriven-part1.ba.md
  markdown/backend/interpretation/astdriven-part1.ma.md
  markdown/backend/interpretation/astdriven-part2.ba.md
  markdown/backend/interpretation/astdriven-part2.ma.md
  markdown/backend/interpretation/syntaxdriven.ba.md
  markdown/backend/interpretation/syntaxdriven.ma.md
Labels: bug, aufgaben, vorlesungen

#110 [ASSIGNMENT] Blatt 01: add 'self' as first parameter to methods
  markdown/assignments/sheet01.ba.md
  markdown/assignments/sheet01.ma.md
Labels: bug, aufgaben

#102 [VL] LR-Parser
  data/ma/schedule.yaml
  markdown/frontend/parsing/bison.ma.md
  markdown/frontend/parsing/finalwords.ma.md
  markdown/frontend/parsing/images/Parser-Automat.tex
  markdown/frontend/parsing/lr-parser1.ma.md
  markdown/frontend/parsing/lr-parser2.ma.md
  markdown/frontend/parsing/parsercombinator.ma.md
  markdown/frontend/parsing/recovery.ma.md
Labels: bug, vorlesungen

#116 [VL] Scopes: Fix link to YT video
  markdown/frontend/semantics/symboltables/scopes.ba.md
  markdown/frontend/semantics/symboltables/scopes.ma.md
Labels: bug, vorlesungen

#118 [VL] Optimization (MA)
  markdown/backend/optimization.ma.md
Labels: vorlesungen
