Repository Compiler-CampusMinden/CB-Vorlesung-Bachelor, pull requests merged in 2024-10, with the labels that each got.

#281 Homework: add sample project
  homework/src/sample_project/.gitattributes
  homework/src/sample_project/.gitignore
  homework/src/sample_project/build.gradle
  homework/src/sample_project/gradle/wrapper/gradle-wrapper.jar
  homework/src/sample_project/gradle/wrapper/gradle-wrapper.properties
  homework/src/sample_project/gradlew
  homework/src/sample_project/gradlew.bat
  homework/src/sample_project/readme.md
  homework/src/sample_project/src/main/antlr/Hello.g4
  homework/src/sample_project/src/main/antlr/my/pkg/HelloPackage.g4
  homework/src/sample_project/src/main/java/Main.java
  homework/src/sample_project/src/test/java/MainTest.java
Labels: aufgaben

#291 Lecture: rework regular languages
  lecture/01-lexing/regular.md
Labels: vorlesungen

#292 Lecture: reduce LL parser session
  lecture/02-parsing/ll-parser.md
Labels: vorlesungen

#293 Lecture: rework CFG and add LL slides
  lecture/02-parsing/cfg.md
Labels: vorlesungen

#294 Homework: rework B01 (RegExp)
  homework/sheet01.md
Labels: aufgaben

#277 Homework: rework B03 (ANTLR)
  homework/sheet03.md
Labels: aufgaben

#278 Homework: rework B04 (Symboltabelle)
  homework/sheet04.md
  homework/sheet04x.md
  homework/src/sample_project/src/main/antlr/MiniC.g4
  readme.md
Labels: aufgaben

#279 Homework: rework B05 (Interpreter)
  homework/sheet05.md
  homework/sheet05x.md
  homework/src/sample_project/src/main/antlr/MiniLisp.g4
  readme.md
Labels: aufgaben

#295 Lecture: fix math (Regular/Lexing)
  lecture/01-lexing/regular.md
Labels: vorlesungen

#296 Lecture: fix math mode in image (CFG)
  lecture/02-parsing/images/Def_PDA.png
  lecture/02-parsing/images/Def_PDA.tex
Labels: bug, vorlesungen

#297 Lecture: add new C++ lessons
  lecture/99-languages/cpp0-basics.md
  lecture/99-languages/cpp1-functions.md
  lecture/99-languages/cpp1-pointer.md
  lecture/99-languages/cpp2-classes.md
  lecture/99-languages/cpp3-big3.md
  lecture/99-languages/cpp4-operators.md
  lecture/99-languages/cpp5-inheritance.md
  lecture/99-languages/cpp6-templates.md
  lecture/99-languages/src/funktionsTemplates.cpp
  lecture/99-languages/src/matrix.cpp
  lecture/99-languages/src/matrix2.cpp
  lecture/99-languages/src/matrix3.cpp
  readme.md
Labels: vorlesungen

#298 Lecture: rework and finalise CFG
  lecture/02-parsing/cfg.md
Labels: vorlesungen

#299 Homework: rework B02 (CFG)
  homework/sheet02.md
Labels: aufgaben

#300 Orga: postpone lab for B01 by one week (S5 only)
  readme.md
Labels: orga

#301 Homework: improve MiniLisp grammar (B05)
  homework/sheet05.md
  homework/src/sample_project/src/main/antlr/MiniLispA.g4
  homework/src/sample_project/src/main/antlr/MiniLispB.g4
Labels: aufgaben
